### ISSUE TITLE
There is an issue with the Client side

### ISSUE THREAD

**Issue by pedram7sd** [anilshanbhag/videochat#2]
adrien@adrien-VirtualBox:~/Desktop/videochat/videochat-master$ python client.py client
OpenCV Error: Bad argument (Array should be CvMat or IplImage) in cvGetSize, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp, line 1238
Traceback (most recent call last):
  File "client.py", line 31, in <module>
    client.connect()
  File "client.py", line 15, in connect
    frame=self.videofeed.get_frame()
  File "/home/adrien/Desktop/videochat/videochat-master/videofeed.py", line 25, in get_frame
    jpegImg= Image.fromstring("RGB",cv.GetSize(self.frame),self.frame.tostring())
cv2.error: Array should be CvMat or IplImage
adrien@adrien-VirtualBox:~/Desktop/videochat/videochat-master

**Comment by anilshanbhag** [comment]
Can you try again ? Things are working now. 
Feel free to reopen if things don't work.
